resources:
  - url: http://127.0.0.1:5000/flipdown-timer-card.js
    type: module
views:
  - cards:
      - type: custom:boilerplate-card
        name: Boilerplate Card Development
        entity: sun.sun
        test_gui: true
